---

- name: Add Deb822 Repos
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
  when: item.name is defined
  with_items: "{{ _filebeat_install.apt.deb822_repository | default([]) }}"

- name: Install Filebeat
  ansible.builtin.apt:
    name: "{{ _filebeat_install.apt.package.name }}={{ _filebeat_install.apt.package.version }}"
    state: present
    update_cache: true

  # Configuration not present during Packer run
- name: Configure Service to NOT autostart
  ansible.builtin.service:
    name: filebeat
    state: stopped
    enabled: no
