---

- name: Install Elastic.co package key
  ansible.builtin.apt_key:
    id: "{{ _filebeat_install.apt.key_id }}"
    url: "{{ _filebeat_install.apt.key_url }}"
    state: present

- name: Add Elastic.co repository
  ansible.builtin.apt_repository:
    repo: "{{ _filebeat_install.apt.repo_line }}"
    state: present

- name: Install Filebeat
  ansible.builtin.apt:
    name: "{{ _filebeat_install.apt.package.name }}={{ _filebeat_install.apt.package.version }}"
    state: present

  # Configuration not present during Packer run
- name: Configure Service to NOT autostart
  ansible.builtin.service:
    name: filebeat
    state: stopped
    enabled: no
