---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include vars of defaults/main.yml
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"

    - name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        # AMD64: Filebeat 6, ARM64: Filebeat 7
        _filebeat_install: "{{ (ansible_architecture == 'x86_64') | ternary(_filebeat_6, _filebeat_7) }}"
